version: "3.9"

services:
  app:
    build: .
    container_name: cause-list-checker
    ports:
      - "3080:3080"
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
